language: java
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
    -v '\[')
deploy:
  name: $project_version
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Hb3O0/2GUkOqjRNfo599EqeLt8ISnirTDw7QgalmTcQZoYaIZRpuqzlr7aApwQP7CZLAGBqhC4ukGPsN4ekPdTS4sDMLPvxfZp2X+mGUjDlnTwULOKtfyr562lnqbLr5RTs23oVvzL7FKMO3xay+fgOEXas7M6N2YFg1/a7qymMg4g4wDjUr/x71CEcp7QRvLQ7xFPZOdbUVpitimYToOdiTR4Va+PIpQ6e9ra9/aOPKBEhG/RpnkZ3ojOVro9zVMUf0oDb1IqRffAifyhNsu7MzsTnCxJ1UICZKBTLHWbs0TY/Htrtq6Lh97JJ0pZL1EtIgBknpGmf72hdy8gJX6IB1gQtUw+TLPHG36FZJDl8s4rPlKU1U+Y9jyav1jZBh/x2xR4sfSo8Wj4NRgt5ui0vbDMBqpPs46wSVKyk7iq5f34aNnxCei+C5PB4NGJl33XDvaSNJwFRRYvs53Y0fVus59OqDBWxPNXcNub0AI/H51BpHnb9k1vkicg1rOMQQ+WIxi3r1JFLalPThhhAby/gfe6/JmvJgvpyYQh3eSg43itwBK3VIhfs4xLYmGx+Eb9A0SalMSIcH6CmzU3s48LwEhF/knMiiUp1S/3OScUQ4UuxkCfRaRksHIQfykMie56pFl9TqGX0MthmTx6MbLvcjZbJhdl16aOoisLBNgJU=
  file: target/cqrs-lib-$project_version.jar
  on:
    repo: ec-yakindu/cqrs-lib

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
  mvn --settings ..maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

script:
  mvn clean deploy --settings ..maven.xml -DskipTests=true -B -U -Prelease
